services:
  mongodb:
    image: mongodb/mongodb-atlas-local:latest
    container_name: mongodb_vector_local
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_mongot:/data/mongot
      
volumes:
  mongodb_data:
  mongodb_mongot: